import { z } from "zod";

// Helper to validate JSON fields (can be array, object, or null)
const jsonSchema = z
  .union([
    z.array(z.any()),
    z.record(z.string(), z.any()),
    z.null(),
    z.undefined(),
  ])
  .optional();

export const createActiveSubstanceSchema = z.object({
  // Core identification (required)
  activeSubstance: z.string().min(1),

  // Core optional fields
  concentration: z.string().optional(),
  classification: z.string().optional(),
  dosageForm: z.string().optional(),
  indication: z.string().optional(),

  // Dosage Fields
  adultDoseMaxPerDay: z.string().optional(),
  adultDoseMgPerKg: z.string().optional(),
  doseInKg: z.string().optional(),
  pediatricDose: z.string().optional(),

  // Content Fields
  glucoseContent: z.string().optional(),
  lactoseContent: z.string().optional(),
  fructoseContent: z.string().optional(),
  preservativesInOcularProducts: z.string().optional(),
  eliminationPathway: z.string().optional(),

  // Warning Fields
  contraindications: jsonSchema,
  pregnancyWarning: z.string().optional(),
  lactationWarning: z.string().optional(),
  reproductiveWarningFemale: z.string().optional(),
  reproductiveWarningMale: z.string().optional(),
  specialPopulationChildren: z.string().optional(),
  specialPopulationElderly: z.string().optional(),
  ethnicAction: z.string().optional(),
  hepaticWarning: z.string().optional(),
  renalWarning: z.string().optional(),
  medicationErrorWarning: z.string().optional(),
  carcinogenicityMutagenicity: z.string().optional(),
  gitWarning: z.string().optional(),
  metabolismWarning: z.string().optional(),
  pulmonaryWarning: z.string().optional(),
  immuneSystemWarning: z.string().optional(),
  infectionWarning: z.string().optional(),
  bloodWarning: z.string().optional(),
  vascularWarning: z.string().optional(),
  electrolyteImbalanceWarning: z.string().optional(),
  cardiacWarning: z.string().optional(),
  psychiatricWarning: z.string().optional(),
  nervousSystemWarning: z.string().optional(),
  skinConnectiveTissueWarning: z.string().optional(),
  musculoSkeletalWarning: z.string().optional(),
  eyeDisordersWarning: z.string().optional(),
  earDisordersWarning: z.string().optional(),

  // Drug Interaction Fields (JSON arrays)
  interactionVitaminsFood: jsonSchema,
  interactionBisphosphonates: jsonSchema,
  interactionAlcohol: jsonSchema,
  interactionMuscleRelaxant: jsonSchema,
  interactionRetinoids: jsonSchema,
  interactionCorticosteroids: jsonSchema,
  interactionXanthines: jsonSchema,
  interactionSympathomimetics: jsonSchema,
  interactionAnticholinergic: jsonSchema,
  interactionChemotherapy: jsonSchema,
  interactionAntibiotics: jsonSchema,
  interactionHormones: jsonSchema,
  interactionStatins: jsonSchema,
  interactionAntihypertensive: jsonSchema,
  interactionAntidiuretics: jsonSchema,
  interactionAntidepressant: jsonSchema,
  interactionAntidiabetic: jsonSchema,
  interactionLowBloodSugarAgents: jsonSchema,
  interactionDigoxin: jsonSchema,
  interactionAnticoagulant: jsonSchema,
  interactionNSAIDs: jsonSchema,
  interactionImmunosuppressive: jsonSchema,
  interactionAntacids: jsonSchema,
  interactionUricosurics: jsonSchema,
  interactionProtectants: jsonSchema,
  interactionAntiParkinson: jsonSchema,
  interactionHIVProtease: jsonSchema,
  ironChelator: z.string().optional(),
  interactionBloodProduct: jsonSchema,
  interactionVaccines: jsonSchema,
  interactionAnthelmintics: jsonSchema,
  interactionPDE5Inhibitors: jsonSchema,
  interferenceLabTests: z.string().optional(),
  effectOnDriving: z.string().optional(),

  // Side Effects Fields (JSON arrays by frequency) - Very Common
  veryCommonGIT: jsonSchema,
  veryCommonBlood: jsonSchema,
  veryCommonVascular: jsonSchema,
  veryCommonCardiac: jsonSchema,
  veryCommonMusculoskeletal: jsonSchema,
  veryCommonNervousSystem: jsonSchema,
  veryCommonEye: jsonSchema,
  veryCommonMetabolism: jsonSchema,
  veryCommonEar: jsonSchema,
  veryCommonRespiratory: jsonSchema,
  veryCommonSkin: jsonSchema,
  veryCommonInfection: jsonSchema,
  veryCommonPsychiatric: jsonSchema,
  veryCommonRenal: jsonSchema,
  veryCommonHepatic: jsonSchema,
  veryCommonGeneral: jsonSchema,

  // Side Effects Fields - Common
  commonGIT: jsonSchema,
  commonVascular: jsonSchema,
  commonInfections: jsonSchema,
  commonRespiratory: jsonSchema,
  commonCardiac: jsonSchema,
  commonBlood: jsonSchema,
  commonSkin: jsonSchema,
  commonEye: jsonSchema,
  commonEar: jsonSchema,
  commonMetabolism: jsonSchema,
  commonGeneral: jsonSchema,
  commonHepatobiliary: jsonSchema,
  commonImmunity: jsonSchema,
  commonPsychiatric: jsonSchema,
  commonNervousSystem: jsonSchema,
  commonRenal: jsonSchema,
  commonMusculoskeletal: jsonSchema,

  // Side Effects Fields - Uncommon
  uncommonNervous: jsonSchema,
  uncommonInfections: jsonSchema,
  uncommonPsychiatric: jsonSchema,
  uncommonEye: jsonSchema,
  uncommonRespiratory: jsonSchema,
  uncommonSkin: jsonSchema,
  uncommonRenal: jsonSchema,
  uncommonHepatobiliary: jsonSchema,
  uncommonVascular: jsonSchema,
  uncommonGIT: jsonSchema,
  uncommonMusculoskeletal: jsonSchema,
  uncommonMetabolism: jsonSchema,
  uncommonEar: jsonSchema,
  uncommonCardiac: jsonSchema,
  uncommonBlood: jsonSchema,
  uncommonImmunity: jsonSchema,
  uncommonGeneral: jsonSchema,

  // Side Effects Fields - Rare
  rareEar: jsonSchema,
  rareBlood: jsonSchema,
  rareGIT: jsonSchema,
  rareHepatic: jsonSchema,
  rareInfections: jsonSchema,
  rareCardiac: jsonSchema,
  rareVascular: jsonSchema,
  rareImmune: jsonSchema,
  rareMetabolism: jsonSchema,
  rareNervous: jsonSchema,
  rareMusculoskeletal: jsonSchema,
  rarePsychiatric: jsonSchema,
  rareEye: jsonSchema,
  rareRenal: jsonSchema,
  rareSkin: jsonSchema,
  rareRespiratory: jsonSchema,
  rareEndocrine: jsonSchema,
  rareGeneral: jsonSchema,

  // Side Effects Fields - Very Rare
  veryRareVascular: jsonSchema,
  veryRareEndocrine: jsonSchema,
  veryRareNervous: jsonSchema,
  veryRarePsychiatric: jsonSchema,
  veryRareEye: jsonSchema,
  veryRareMusculoskeletal: jsonSchema,
  veryRareBlood: jsonSchema,
  veryRareCardiac: jsonSchema,
  veryRareImmune: jsonSchema,
  veryRareEar: jsonSchema,
  veryRareRenal: jsonSchema,
  veryRareGIT: jsonSchema,
  veryRareHepatobiliary: jsonSchema,
  veryRareInfections: jsonSchema,
  veryRareRespiratory: jsonSchema,
  veryRareSkin: jsonSchema,
  veryRareGeneral: jsonSchema,
  veryRareMetabolism: jsonSchema,

  // Side Effects Fields - Unknown
  unknownNervous: jsonSchema,
  unknownMusculoskeletal: jsonSchema,
  unknownPsychiatric: jsonSchema,
  unknownHepatobiliary: jsonSchema,
  unknownRenal: jsonSchema,
  unknownSkin: jsonSchema,
  unknownRespiratory: jsonSchema,
  unknownImmune: jsonSchema,
  unknownVascular: jsonSchema,
  unknownEar: jsonSchema,
  unknownGIT: jsonSchema,
  unknownGeneral: jsonSchema,
  unknownMetabolism: jsonSchema,
  unknownEye: jsonSchema,
  unknownBlood: jsonSchema,
  unknownCardiac: jsonSchema,
  unknownInfections: jsonSchema,
  unknownEndocrine: jsonSchema,

  // Additional Fields
  additiveRMM: z.string().optional(),
  pregnancyCategory: z.string().optional(),
  additionalMonitoring: z.string().optional(),
  highlightedWarning: z.string().optional(),
  version: z.number().int().positive().optional(),
  isActive: z.boolean().optional(),
});

export const updateActiveSubstanceSchema = createActiveSubstanceSchema
  .partial()
  .extend({
    activeSubstance: z.string().min(1).optional(), // Make activeSubstance optional for updates
  });
